name: Github Tests

on: [push]

jobs:
    build-and-tests:
        runs-on: ubuntu-latests
        
        steps:
            - uses: actions/checkout@v2
            
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'
                
            - name: Install Make
              run: sudo apt-get install make
              
            - name: Install Dependencies
              run: make Install
              
            - name: Build Project
              run: make build

            - name: Run Lint
              run: make lint

            - name: Run Tests
              run: make test
